name: Deploy to AWS

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Create deployment package
      run: |
        # Use the final deployment script that handles tar file change errors
        ./deploy-final.sh
        
    - name: Deploy to AWS
      run: |
        # Your deployment commands here
        echo "Deployment package created successfully"
        ls -la deployment-package.tar.gz
        
        # Example: Deploy to S3 or EC2
        # aws s3 cp deployment-package.tar.gz s3://your-bucket/
        # or
        # aws ec2 create-instance --image-id ami-12345678 --instance-type t2.micro 